-- =====================================================
-- INSERT 80 CLIENTS - SAFE INSERTION
-- =====================================================
USE freelance_gig_exchange;

INSERT INTO clients (name, email, organization, location, member_since)
VALUES
('Global Tech Pvt Ltd', 'globaltech1@company.com', 'Global Tech Pvt Ltd', 'Mumbai', '2021-01-15'),
('NextGen Solutions', 'contact@nextgensolutions.com', 'NextGen Solutions', 'Bangalore', '2022-05-20'),
('DataWave Analytics', 'info@datawave.in', 'DataWave Analytics', 'Delhi', '2021-07-10'),
('Creative Minds Studio', 'hello@creativeminds.in', 'Creative Minds Studio', 'Chennai', '2023-02-01'),
('CloudX Innovations', 'cloudx@innovations.com', 'CloudX Innovations', 'Pune', '2021-11-05'),
('SecureSoft Systems', 'sales@securesoft.com', 'SecureSoft Systems', 'Hyderabad', '2022-03-18'),
('EduLearn Tech', 'support@edulearn.in', 'EduLearn Tech', 'Kolkata', '2022-09-12'),
('Urban Services', 'contact@urbanservices.in', 'Urban Services', 'Ahmedabad', '2023-06-01'),
('HealthTrack Solutions', 'info@healthtrack.in', 'HealthTrack Solutions', 'Bangalore', '2021-12-25'),
('MarketFlow Ltd', 'business@marketflow.com', 'MarketFlow Ltd', 'Mumbai', '2022-08-15'),
('TechVenture Inc', 'info@techventure.com', 'TechVenture Inc', 'Delhi', '2021-03-20'),
('Digital Dynamics', 'contact@digitaldynamics.in', 'Digital Dynamics', 'Bangalore', '2022-06-10'),
('InnovateHub', 'hello@innovatehub.com', 'InnovateHub', 'Pune', '2021-09-15'),
('SmartSolutions', 'info@smartsolutions.in', 'SmartSolutions', 'Chennai', '2022-11-30'),
('CodeCraft Technologies', 'sales@codecraft.com', 'CodeCraft Technologies', 'Hyderabad', '2021-04-25'),
('DataSphere Analytics', 'contact@datasphere.in', 'DataSphere Analytics', 'Mumbai', '2022-07-18'),
('WebWorks Studio', 'info@webworks.in', 'WebWorks Studio', 'Bangalore', '2021-10-10'),
('AppGenius Labs', 'hello@appgenius.com', 'AppGenius Labs', 'Delhi', '2023-01-05'),
('CloudBridge Solutions', 'contact@cloudbridge.in', 'CloudBridge Solutions', 'Pune', '2022-02-14'),
('TechNova Systems', 'info@technova.com', 'TechNova Systems', 'Chennai', '2021-05-30'),
('Digital Edge', 'sales@digitaledge.in', 'Digital Edge', 'Hyderabad', '2022-09-22'),
('Innovation Labs', 'contact@innovationlabs.com', 'Innovation Labs', 'Mumbai', '2021-08-12'),
('CodeForge Technologies', 'info@codeforge.in', 'CodeForge Technologies', 'Bangalore', '2022-12-05'),
('TechMasters', 'hello@techmasters.com', 'TechMasters', 'Delhi', '2021-11-20'),
('DataPulse Analytics', 'contact@datapulse.in', 'DataPulse Analytics', 'Pune', '2022-04-15'),
('WebCraft Solutions', 'info@webcraft.com', 'WebCraft Solutions', 'Chennai', '2021-06-25'),
('AppSphere', 'sales@appsphere.in', 'AppSphere', 'Hyderabad', '2022-10-08'),
('CloudSync Technologies', 'contact@cloudsync.com', 'CloudSync Technologies', 'Mumbai', '2021-09-18'),
('TechFlow Systems', 'info@techflow.in', 'TechFlow Systems', 'Bangalore', '2022-03-10'),
('Digital Nexus', 'hello@digitalnexus.com', 'Digital Nexus', 'Delhi', '2021-12-22'),
('InnovateX Labs', 'contact@innovatex.in', 'InnovateX Labs', 'Pune', '2022-07-05'),
('CodeStream Technologies', 'info@codestream.com', 'CodeStream Technologies', 'Chennai', '2021-04-12'),
('DataFlow Analytics', 'sales@dataflow.in', 'DataFlow Analytics', 'Hyderabad', '2022-11-18'),
('WebVenture Studio', 'contact@webventure.com', 'WebVenture Studio', 'Mumbai', '2021-07-25'),
('AppCraft Solutions', 'info@appcraft.in', 'AppCraft Solutions', 'Bangalore', '2022-05-20'),
('CloudTech Innovations', 'hello@cloudtech.com', 'CloudTech Innovations', 'Delhi', '2021-10-15'),
('TechPulse Systems', 'contact@techpulse.in', 'TechPulse Systems', 'Pune', '2022-08-28'),
('Digital Forge', 'info@digitalforge.com', 'Digital Forge', 'Chennai', '2021-03-08'),
('InnovateLab', 'sales@innovatelab.in', 'InnovateLab', 'Hyderabad', '2022-12-12'),
('CodeWave Technologies', 'contact@codewave.com', 'CodeWave Technologies', 'Mumbai', '2021-06-20'),
('DataSync Analytics', 'info@datasync.in', 'DataSync Analytics', 'Bangalore', '2022-09-15'),
('WebGenius Studio', 'hello@webgenius.com', 'WebGenius Studio', 'Delhi', '2021-11-28'),
('AppFlow Solutions', 'contact@appflow.in', 'AppFlow Solutions', 'Pune', '2022-04-22'),
('CloudForge Technologies', 'info@cloudforge.com', 'CloudForge Technologies', 'Chennai', '2021-08-05'),
('TechSync Systems', 'sales@techsync.in', 'TechSync Systems', 'Hyderabad', '2022-01-18'),
('Digital Pulse', 'contact@digitalpulse.com', 'Digital Pulse', 'Mumbai', '2021-05-12'),
('InnovateCore Labs', 'info@innovatecore.in', 'InnovateCore Labs', 'Bangalore', '2022-10-25'),
('CodePulse Technologies', 'hello@codepulse.com', 'CodePulse Technologies', 'Delhi', '2021-09-30'),
('DataVenture Analytics', 'contact@dataventure.in', 'DataVenture Analytics', 'Pune', '2022-06-15'),
('WebSync Studio', 'info@websync.com', 'WebSync Studio', 'Chennai', '2021-12-08'),
('AppSync Solutions', 'sales@appsync.in', 'AppSync Solutions', 'Hyderabad', '2022-03-25'),
('CloudPulse Technologies', 'contact@cloudpulse.com', 'CloudPulse Technologies', 'Mumbai', '2021-07-18'),
('TechVenture Systems', 'info@techventure.in', 'TechVenture Systems', 'Bangalore', '2022-11-05'),
('Digital Core', 'hello@digitalcore.com', 'Digital Core', 'Delhi', '2021-04-22'),
('InnovateFlow Labs', 'contact@innovateflow.in', 'InnovateFlow Labs', 'Pune', '2022-08-12'),
('CodeCore Technologies', 'info@codecore.com', 'CodeCore Technologies', 'Chennai', '2021-10-28'),
('DataCore Analytics', 'sales@datacore.in', 'DataCore Analytics', 'Hyderabad', '2022-05-08'),
('WebCore Studio', 'contact@webcore.com', 'WebCore Studio', 'Mumbai', '2021-08-15'),
('AppCore Solutions', 'info@appcore.in', 'AppCore Solutions', 'Bangalore', '2022-12-20'),
('CloudCore Technologies', 'hello@cloudcore.com', 'CloudCore Technologies', 'Delhi', '2021-06-10'),
('TechCore Systems', 'contact@techcore.in', 'TechCore Systems', 'Pune', '2022-09-28'),
('Digital Sync', 'info@digitalsync.com', 'Digital Sync', 'Chennai', '2021-11-15'),
('InnovateSync Labs', 'sales@innovatesync.in', 'InnovateSync Labs', 'Hyderabad', '2022-04-05'),
('CodeSync Technologies', 'contact@codesync.com', 'CodeSync Technologies', 'Mumbai', '2021-09-22'),
('DataSync Pro Analytics', 'info@datasyncpro.in', 'DataSync Pro Analytics', 'Bangalore', '2022-07-18'),
('WebSync Pro Studio', 'hello@websyncpro.com', 'WebSync Pro Studio', 'Delhi', '2021-12-25'),
('AppSync Pro Solutions', 'contact@appsyncpro.in', 'AppSync Pro Solutions', 'Pune', '2022-10-12'),
('CloudSync Pro Technologies', 'info@cloudsyncpro.com', 'CloudSync Pro Technologies', 'Chennai', '2021-05-18'),
('TechSync Pro Systems', 'sales@techsyncpro.in', 'TechSync Pro Systems', 'Hyderabad', '2022-08-28'),
('Digital Sync Pro', 'contact@digitalsyncpro.com', 'Digital Sync Pro', 'Mumbai', '2021-07-30'),
('InnovateSync Pro Labs', 'info@innovatesyncpro.in', 'InnovateSync Pro Labs', 'Bangalore', '2022-11-15'),
('CodeSync Pro Technologies', 'hello@codesyncpro.com', 'CodeSync Pro Technologies', 'Delhi', '2021-04-08'),
('DataFlow Pro Analytics', 'contact@dataflowpro.in', 'DataFlow Pro Analytics', 'Pune', '2022-09-22'),
('WebFlow Pro Studio', 'info@webflowpro.com', 'WebFlow Pro Studio', 'Chennai', '2021-10-15'),
('AppFlow Pro Solutions', 'sales@appflowpro.in', 'AppFlow Pro Solutions', 'Hyderabad', '2022-06-28'),
('CloudFlow Pro Technologies', 'contact@cloudflowpro.com', 'CloudFlow Pro Technologies', 'Mumbai', '2021-08-20'),
('TechFlow Pro Systems', 'info@techflowpro.in', 'TechFlow Pro Systems', 'Bangalore', '2022-12-05'),
('Digital Flow Pro', 'hello@digitalflowpro.com', 'Digital Flow Pro', 'Delhi', '2021-11-28'),
('InnovateFlow Pro Labs', 'contact@innovateflowpro.in', 'InnovateFlow Pro Labs', 'Pune', '2022-05-15'),
('CodeFlow Pro Technologies', 'info@codeflowpro.com', 'CodeFlow Pro Technologies', 'Chennai', '2021-09-10');

COMMIT;


